name: ci_aop

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - aop

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Preparation for ./gradlew
        run: |
          java --version
          chmod u+x ./gradlew
      - name: spotlessCheck
        run: ./gradlew spotlessCheck
      - name: test
        run: ./gradlew test
